model:
  type: 'SourceOnlySegmentor'
dataset:
  num_classes: 19
  source:
    type: 'GTAV'
  val:
    type: 'Cityscapes'
    json_path: '../data/cityscapes_val.json'
    image_dir: '../data/cityscapes'
validate:
  resize_sizes: [ [ 768, 1536 ] ]
  is_flip: False
  batch_size: 2
  color_mask_dir_path: None